// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1jiyI90wmKjcNWbExs64POWoF2T4-Qvs',
    appId: '1:486279149628:web:fec94cac1c857a2f86ab39',
    messagingSenderId: '486279149628',
    projectId: 'tourismapp-da749',
    authDomain: 'tourismapp-da749.firebaseapp.com',
    storageBucket: 'tourismapp-da749.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKfxw9wFD0X3PYf4gTDfL4NJG3AlgyPZ8',
    appId: '1:486279149628:android:27932a43476baf2686ab39',
    messagingSenderId: '486279149628',
    projectId: 'tourismapp-da749',
    storageBucket: 'tourismapp-da749.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUvbGnUj-S-zOzQjMMAxd4OIMVqdJFS70',
    appId: '1:486279149628:ios:4ce13df39c69c3ec86ab39',
    messagingSenderId: '486279149628',
    projectId: 'tourismapp-da749',
    storageBucket: 'tourismapp-da749.appspot.com',
    iosBundleId: 'com.example.tourismApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUvbGnUj-S-zOzQjMMAxd4OIMVqdJFS70',
    appId: '1:486279149628:ios:75f0ba6e6178c3e286ab39',
    messagingSenderId: '486279149628',
    projectId: 'tourismapp-da749',
    storageBucket: 'tourismapp-da749.appspot.com',
    iosBundleId: 'com.example.tourismApp.RunnerTests',
  );
}
